### ISSUE TITLE
Using aliases of the config parameter gives an error

### ISSUE THREAD

**Issue by gardar** [maxhoesel/ansible-collection-caddy#11]
The aliases for the `config` parameter aren't working as expected

https://github.com/maxhoesel/ansible-collection-caddy/blob/c7599f0a471fec75c29ad72d075b25c44a1581d5/plugins/modules/caddy_config.py#L146

When I try to load the config with the alias `content` I get this error:

```
Traceback (most recent call last):
  File "/tmp/ansible/ansible-tmp-1652205555.78-2446572-24742954918398/AnsiballZ_caddy_config.py", line 102, in <module>
    _ansiballz_main()
  File "/tmp/ansible/ansible-tmp-1652205555.78-2446572-24742954918398/AnsiballZ_caddy_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible/ansible-tmp-1652205555.78-2446572-24742954918398/AnsiballZ_caddy_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.maxhoesel.caddy.plugins.modules.caddy_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_maxhoesel.caddy.caddy_config_payload_nqxtz613/ansible_maxhoesel.caddy.caddy_config_payload.zip/ansible_collections/maxhoesel/caddy/plugins/modules/caddy_config.py", line 169, in <module>
  File "/tmp/ansible_maxhoesel.caddy.caddy_config_payload_nqxtz613/ansible_maxhoesel.caddy.caddy_config_payload.zip/ansible_collections/maxhoesel/caddy/plugins/modules/caddy_config.py", line 165, in main
  File "/tmp/ansible_maxhoesel.caddy.caddy_config_payload_nqxtz613/ansible_maxhoesel.caddy.caddy_config_payload.zip/ansible_collections/maxhoesel/caddy/plugins/modules/caddy_config.py", line 158, in run_module
  File "/tmp/ansible_maxhoesel.caddy.caddy_config_payload_nqxtz613/ansible_maxhoesel.caddy.caddy_config_payload.zip/ansible_collections/maxhoesel/caddy/plugins/modules/caddy_config.py", line 105, in create_or_update_config
KeyError: 'config'

```

I also confirmed this going back a few commits to a version before the recent changes (python2 and `create_path`) but the error is also present there, I just must have used the parameter as `config` before and not as `content`.

**Comment by maxhoesel** [comment]
Fixed in #12, thanks for the heads-up!
